app_port: 8000
migrates_folder: migrations
cryptocompare_api_key:
  - abc
  - asd
conf_db:
  address: 127.0.0.1
  port: 5449
  user: aHAjeK
  pass: AOifjwelmc8dw
  db_name: sybill
  max_connections: 10
telegramist:
  token: 123456789:ABC-DEF1234ghIkl-zyx57W2v1u123ew11
  chat_id: 123456789
